---

- block:
  - name: Setup RADIUS authentication policy for SMS Passcode
    netscaler_raw:
      url: "{{ netscaler_url }}"
      username: "{{ netscaler_username }}"
      password: "{{ netscaler_password }}"
      objecttype: "macroapi"
      data:
        authenticationradiusaction:
          name: act_auth_radius_smspasscode
          serverip: "{{ netscaler_smspasscode_server }}"
          serverport: 1812
          authtimeout: 3
          radkey: "{{ netscaler_smspasscode_radkey }}"
          radnasip: ENABLED
          radnasid: NetScaler
          radvendorid: "1"
          radattributetype: 99
          radgroupsprefix: CTXUserGroups=
          radgroupseparator: ","
          accounting: "ON"
          callingstationid: ENABLED
        authenticationradiuspolicy:
          - name: pol_auth_radius_smspasscode
            rule: ns_true
            reqaction: act_auth_radius_smspasscode
          - name: pol_auth_radius_smspasscode_receiver
            rule: "REQ.HTTP.HEADER User-Agent CONTAINS CitrixReceiver"
            reqaction: act_auth_radius_smspasscode
          - name: pol_auth_radius_smspasscode_not_receiver
            rule: "REQ.HTTP.HEADER User-Agent NOTCONTAINS CitrixReceiver"
            reqaction: act_auth_radius_smspasscode
  # maybe optional polcies right here
  when: netscaler_smspasscode_server is defined and
        netscaler_smspasscode_radkey is defined

