---

netscaler_common_features: lb cs ssl rewrite responder

# defaults file for netscaler_configs
netscaler_common_config:
  nsconfig:
    cip: ENABLED
    cipheader: X-Forwarded-For
    cookieversion: 1
    securecookie: ENABLED
#    timezone: "GMT+01:00-CET-Europe/Berlin"

# default secure cipherset
netscaler_common_sslcipher_sslciphersuite_binding:
  sslcipher_sslciphersuite_binding:
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-ECDSA-CHACHA20-POLY1305"
      "cipherpriority": "1"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-RSA-CHACHA20-POLY1305"
      "cipherpriority": "2"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-RSA-AES256-GCM-SHA384"
      "cipherpriority": "3"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-ECDSA-AES256-GCM-SHA384"
      "cipherpriority": "4"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-DHE-RSA-AES256-GCM-SHA384"
      "cipherpriority": "5"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-RSA-AES128-GCM-SHA256"
      "cipherpriority": "6"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-ECDSA-AES128-GCM-SHA256"
      "cipherpriority": "7"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-DHE-RSA-AES128-GCM-SHA256"
      "cipherpriority": "8"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-ECDSA-AES256-SHA384"
      "cipherpriority": "9"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-RSA-AES-256-SHA384"
      "cipherpriority": "10"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-ECDSA-AES128-SHA256"
      "cipherpriority": "11"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1.2-ECDHE-RSA-AES-128-SHA256"
      "cipherpriority": "12"
    # remove if tls 1.0 is not needed
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-ECDHE-RSA-AES256-SHA"
      "cipherpriority": "13"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-ECDHE-RSA-AES128-SHA"
      "cipherpriority": "14"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-DHE-RSA-AES-256-CBC-SHA"
      "cipherpriority": "15"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-DHE-RSA-AES-128-CBC-SHA"
      "cipherpriority": "16"
    # insecure, but may break xenmobile
    # remove this in a future version
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-AES-256-CBC-SHA"
      "cipherpriority": "17"
    - "ciphergroupname": "CUSTOM_SECURE"
      "ciphername": "TLS1-AES-128-CBC-SHA"
      "cipherpriority": "18"
