---

- name: Create vServer and service group
  netscaler_raw:
    url: "{{ netscaler_url }}"
    username: "{{ netscaler_username }}"
    password: "{{ netscaler_password }}"
    method: "post"
    objecttype: "macroapi"
    data:
      servicegroup:
        - servicegroupname: sg_{{ outer_item.beproto }}_{{ outer_item.name }}
          servicetype: "{{ outer_item.beproto }}"
      lbvserver:
        - name: "vs_lb_{{ outer_item.feproto }}_{{ outer_item.name }}"
          ipv46: "{{ outer_item.vip }}"
          port: "{{ outer_item.port }}"
          servicetype: "{{ outer_item.feproto }}"
          lbmethod: LEASTCONNECTION
          persistencetype: SOURCEIP
          timeout: 2
      lbvserver_servicegroup_binding:
        - name: "vs_lb_{{ outer_item.feproto }}_{{ outer_item.name }}"
          servicegroupname: "sg_{{ outer_item.beproto }}_{{ outer_item.name }}"

- name: Bind members to the service group
  netscaler_raw:
    url: "{{ netscaler_url }}"
    username: "{{ netscaler_username }}"
    password: "{{ netscaler_password }}"
    method: "post"
    objecttype: "macroapi"
    data:
      servicegroup_servicegroupmember_binding:
        - servicegroupname: "sg_{{ outer_item.beproto }}_{{ outer_item.name }}"
          servername: "{{ item.server }}"
          port: "{{ item.port | default(outer_item.port) }}"
  with_items: "{{ outer_item.servers }}"

- name: Binding SSL certificates to the vServer
  netscaler_raw:
    url: "{{ netscaler_url }}"
    username: "{{ netscaler_username }}"
    password: "{{ netscaler_password }}"
    objecttype: "macroapi"
    data:
      sslvserver_sslcertkey_binding:
        - vservername: "vs_lb_{{ outer_item.feproto }}_{{ outer_item.name }}"
          certkeyname: "{{ item.name }}"
          snicert: "{{ item.snicert | default(false) }}"
  with_items: "{{ outer_item.certkey }}"
  when: outer_item.certkey is defined