---

- name: Creating a generic Content Switching vServer for HTTPS to HTTPS redirects
  netscaler_raw:
    url: "{{ netscaler_url }}"
    username: "{{ netscaler_username }}"
    password: "{{ netscaler_password }}"
    method: "post"
    objecttype: "macroapi"
    data:
      responderaction:
        name: act_responder_generic_redirect
        type: redirect
        target: '"https://" + HTTP.REQ.HOSTNAME.HTTP_URL_SAFE + HTTP.REQ.URL.HTTP_URL_SAFE'
        responsestatuscode: 301
      responderpolicy:
        name: pol_responder_generic_redirect
        rule: "true"
        action: act_responder_generic_redirect
        comment: Generic redirect from HTTP to HTTPS

- block:
  - name: Creating a generic Content Switching vServer for HTTPS to HTTPS redirects
    netscaler_raw:
      url: "{{ netscaler_url }}"
      username: "{{ netscaler_username }}"
      password: "{{ netscaler_password }}"
      method: "post"
      objecttype: "macroapi"
      data:
        csvserver:
          name: vs_cs_http_301_{{ item }}
          servicetype: HTTP
          ipv46: "{{ item }}"
          port: 80
          comment: Generic redirect from HTTP to HTTPS 
    with_items: "{{ netscaler_redirect_vips }}"
    
  - name: Binding responder policy to the Content Switching vServer
    netscaler_raw:
      url: "{{ netscaler_url }}"
      username: "{{ netscaler_username }}"
      password: "{{ netscaler_password }}"
      method: "put"
      objecttype: "macroapi"
      data:
        csvserver_responderpolicy_binding:
          name: vs_cs_http_301_{{ item }}
          policyname: pol_responder_generic_redirect
          priority: 100
    with_items: "{{ netscaler_redirect_vips }}"
  when: netscaler_redirect_vips is defined